disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Berlin Science Fiction Book Club"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"

[params.author]
  name = "Berlin Science Fiction Book Club"
  image = "images/logo.png"
  headline = "These *are* the books you're looking for"
  bio = "These *are* the books you're looking for"
  links = [
     { meetup = "https://www.meetup.com/berlin-science-fiction-book-club/" },
     { discourse = "https://forum.berlinscifibook.club/" }
  ]
